package com.esd.db.dao;

import com.esd.db.model.inspector;

public interface inspectorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspector
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    int deleteByPrimaryKey(Integer inspectorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspector
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    int insert(inspector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspector
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    int insertSelective(inspector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspector
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    inspector selectByPrimaryKey(Integer inspectorId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspector
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    int updateByPrimaryKeySelective(inspector record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inspector
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    int updateByPrimaryKey(inspector record);
}