package com.esd.db.dao;

import com.esd.db.model.userLvl;

public interface userLvlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlvl
     *
     * @mbggenerated Wed May 27 09:26:34 CST 2015
     */
    int deleteByPrimaryKey(Integer userLvl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlvl
     *
     * @mbggenerated Wed May 27 09:26:34 CST 2015
     */
    int insert(userLvl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlvl
     *
     * @mbggenerated Wed May 27 09:26:34 CST 2015
     */
    int insertSelective(userLvl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlvl
     *
     * @mbggenerated Wed May 27 09:26:34 CST 2015
     */
    userLvl selectByPrimaryKey(Integer userLvl);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlvl
     *
     * @mbggenerated Wed May 27 09:26:34 CST 2015
     */
    int updateByPrimaryKeySelective(userLvl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table userlvl
     *
     * @mbggenerated Wed May 27 09:26:34 CST 2015
     */
    int updateByPrimaryKey(userLvl record);
}