package com.esd.db.model;

public class District {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.id
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.pid
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.name
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.phone
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.address
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column district.bank
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    private Integer bank;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.id
     *
     * @return the value of district.id
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.id
     *
     * @param id the value for district.id
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.pid
     *
     * @return the value of district.pid
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.pid
     *
     * @param pid the value for district.pid
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.name
     *
     * @return the value of district.name
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.name
     *
     * @param name the value for district.name
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.phone
     *
     * @return the value of district.phone
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.phone
     *
     * @param phone the value for district.phone
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.address
     *
     * @return the value of district.address
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.address
     *
     * @param address the value for district.address
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column district.bank
     *
     * @return the value of district.bank
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public Integer getBank() {
        return bank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column district.bank
     *
     * @param bank the value for district.bank
     *
     * @mbggenerated Tue Oct 14 11:26:21 CST 2014
     */
    public void setBank(Integer bank) {
        this.bank = bank;
    }
}