package com.esd.db.model;

import java.util.Date;

public class fault {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.fault_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Integer faultId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.fault_caption
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String faultCaption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.fault_des
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String faultDes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.create_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.create_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.create_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String createMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.update_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Integer updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.update_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.update_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String updateMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fault.fault_image
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private byte[] faultImage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.fault_id
     *
     * @return the value of fault.fault_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Integer getFaultId() {
        return faultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.fault_id
     *
     * @param faultId the value for fault.fault_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setFaultId(Integer faultId) {
        this.faultId = faultId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.fault_caption
     *
     * @return the value of fault.fault_caption
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getFaultCaption() {
        return faultCaption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.fault_caption
     *
     * @param faultCaption the value for fault.fault_caption
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setFaultCaption(String faultCaption) {
        this.faultCaption = faultCaption == null ? null : faultCaption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.fault_des
     *
     * @return the value of fault.fault_des
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getFaultDes() {
        return faultDes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.fault_des
     *
     * @param faultDes the value for fault.fault_des
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setFaultDes(String faultDes) {
        this.faultDes = faultDes == null ? null : faultDes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.create_id
     *
     * @return the value of fault.create_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.create_id
     *
     * @param createId the value for fault.create_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.create_time
     *
     * @return the value of fault.create_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.create_time
     *
     * @param createTime the value for fault.create_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.create_method
     *
     * @return the value of fault.create_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getCreateMethod() {
        return createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.create_method
     *
     * @param createMethod the value for fault.create_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setCreateMethod(String createMethod) {
        this.createMethod = createMethod == null ? null : createMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.update_id
     *
     * @return the value of fault.update_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.update_id
     *
     * @param updateId the value for fault.update_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.update_time
     *
     * @return the value of fault.update_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.update_time
     *
     * @param updateTime the value for fault.update_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.update_method
     *
     * @return the value of fault.update_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getUpdateMethod() {
        return updateMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.update_method
     *
     * @param updateMethod the value for fault.update_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setUpdateMethod(String updateMethod) {
        this.updateMethod = updateMethod == null ? null : updateMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fault.fault_image
     *
     * @return the value of fault.fault_image
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public byte[] getFaultImage() {
        return faultImage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fault.fault_image
     *
     * @param faultImage the value for fault.fault_image
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setFaultImage(byte[] faultImage) {
        this.faultImage = faultImage;
    }
}