package com.esd.db.model;

import java.util.Date;

public class inspector {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Integer inspectorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_username
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String inspectorUsername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_password
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String inspectorPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.inspector_real_name
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String inspectorRealName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.create_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.create_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.create_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String createMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.update_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Integer updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.update_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.update_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private String updateMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column inspector.version
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private Integer version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_id
     *
     * @return the value of inspector.inspector_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Integer getInspectorId() {
        return inspectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_id
     *
     * @param inspectorId the value for inspector.inspector_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setInspectorId(Integer inspectorId) {
        this.inspectorId = inspectorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_username
     *
     * @return the value of inspector.inspector_username
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getInspectorUsername() {
        return inspectorUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_username
     *
     * @param inspectorUsername the value for inspector.inspector_username
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setInspectorUsername(String inspectorUsername) {
        this.inspectorUsername = inspectorUsername == null ? null : inspectorUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_password
     *
     * @return the value of inspector.inspector_password
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getInspectorPassword() {
        return inspectorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_password
     *
     * @param inspectorPassword the value for inspector.inspector_password
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setInspectorPassword(String inspectorPassword) {
        this.inspectorPassword = inspectorPassword == null ? null : inspectorPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.inspector_real_name
     *
     * @return the value of inspector.inspector_real_name
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getInspectorRealName() {
        return inspectorRealName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.inspector_real_name
     *
     * @param inspectorRealName the value for inspector.inspector_real_name
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setInspectorRealName(String inspectorRealName) {
        this.inspectorRealName = inspectorRealName == null ? null : inspectorRealName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.create_id
     *
     * @return the value of inspector.create_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.create_id
     *
     * @param createId the value for inspector.create_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.create_time
     *
     * @return the value of inspector.create_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.create_time
     *
     * @param createTime the value for inspector.create_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.create_method
     *
     * @return the value of inspector.create_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getCreateMethod() {
        return createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.create_method
     *
     * @param createMethod the value for inspector.create_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setCreateMethod(String createMethod) {
        this.createMethod = createMethod == null ? null : createMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.update_id
     *
     * @return the value of inspector.update_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.update_id
     *
     * @param updateId the value for inspector.update_id
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.update_time
     *
     * @return the value of inspector.update_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.update_time
     *
     * @param updateTime the value for inspector.update_time
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.update_method
     *
     * @return the value of inspector.update_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public String getUpdateMethod() {
        return updateMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.update_method
     *
     * @param updateMethod the value for inspector.update_method
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setUpdateMethod(String updateMethod) {
        this.updateMethod = updateMethod == null ? null : updateMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column inspector.version
     *
     * @return the value of inspector.version
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column inspector.version
     *
     * @param version the value for inspector.version
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setVersion(Integer version) {
        this.version = version;
    }
}