package com.esd.db.model;

public class markTimeMethod {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marktimemethod.id
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marktimemethod.name
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marktimemethod.keywords
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    private String keywords;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column marktimemethod.note
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    private String note;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marktimemethod.id
     *
     * @return the value of marktimemethod.id
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marktimemethod.id
     *
     * @param id the value for marktimemethod.id
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marktimemethod.name
     *
     * @return the value of marktimemethod.name
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marktimemethod.name
     *
     * @param name the value for marktimemethod.name
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marktimemethod.keywords
     *
     * @return the value of marktimemethod.keywords
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marktimemethod.keywords
     *
     * @param keywords the value for marktimemethod.keywords
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column marktimemethod.note
     *
     * @return the value of marktimemethod.note
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column marktimemethod.note
     *
     * @param note the value for marktimemethod.note
     *
     * @mbggenerated Fri Dec 12 10:13:58 CST 2014
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }
}