package com.esd.db.model;

import java.util.Date;

public class pay {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.worker_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Integer workerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.real_name
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private String realName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.bank_card
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private String bankCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.salary
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Double salary;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.taxes
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Double taxes;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.pay_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.mark
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Integer mark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.user_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.create_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.create_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Integer createId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.create_method
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private String createMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.update_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Integer updateId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.update_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.update_method
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    private String updateMethod;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.id
     *
     * @return the value of pay.id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.id
     *
     * @param id the value for pay.id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.worker_id
     *
     * @return the value of pay.worker_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Integer getWorkerId() {
        return workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.worker_id
     *
     * @param workerId the value for pay.worker_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setWorkerId(Integer workerId) {
        this.workerId = workerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.real_name
     *
     * @return the value of pay.real_name
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public String getRealName() {
        return realName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.real_name
     *
     * @param realName the value for pay.real_name
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setRealName(String realName) {
        this.realName = realName == null ? null : realName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.bank_card
     *
     * @return the value of pay.bank_card
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public String getBankCard() {
        return bankCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.bank_card
     *
     * @param bankCard the value for pay.bank_card
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setBankCard(String bankCard) {
        this.bankCard = bankCard == null ? null : bankCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.salary
     *
     * @return the value of pay.salary
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Double getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.salary
     *
     * @param salary the value for pay.salary
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.taxes
     *
     * @return the value of pay.taxes
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Double getTaxes() {
        return taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.taxes
     *
     * @param taxes the value for pay.taxes
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setTaxes(Double taxes) {
        this.taxes = taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.pay_time
     *
     * @return the value of pay.pay_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.pay_time
     *
     * @param payTime the value for pay.pay_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.mark
     *
     * @return the value of pay.mark
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Integer getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.mark
     *
     * @param mark the value for pay.mark
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setMark(Integer mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.user_id
     *
     * @return the value of pay.user_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.user_id
     *
     * @param userId the value for pay.user_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.create_time
     *
     * @return the value of pay.create_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.create_time
     *
     * @param createTime the value for pay.create_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.create_id
     *
     * @return the value of pay.create_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Integer getCreateId() {
        return createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.create_id
     *
     * @param createId the value for pay.create_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setCreateId(Integer createId) {
        this.createId = createId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.create_method
     *
     * @return the value of pay.create_method
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public String getCreateMethod() {
        return createMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.create_method
     *
     * @param createMethod the value for pay.create_method
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setCreateMethod(String createMethod) {
        this.createMethod = createMethod == null ? null : createMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.update_id
     *
     * @return the value of pay.update_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Integer getUpdateId() {
        return updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.update_id
     *
     * @param updateId the value for pay.update_id
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setUpdateId(Integer updateId) {
        this.updateId = updateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.update_time
     *
     * @return the value of pay.update_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.update_time
     *
     * @param updateTime the value for pay.update_time
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.update_method
     *
     * @return the value of pay.update_method
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public String getUpdateMethod() {
        return updateMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.update_method
     *
     * @param updateMethod the value for pay.update_method
     *
     * @mbggenerated Tue Feb 03 11:05:10 CST 2015
     */
    public void setUpdateMethod(String updateMethod) {
        this.updateMethod = updateMethod == null ? null : updateMethod.trim();
    }
}