package com.esd.db.model;

public class taskWithBLOBs extends task {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_wav
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private byte[] taskWav;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_tag
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private byte[] taskTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task.task_textgrid
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    private byte[] taskTextgrid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_wav
     *
     * @return the value of task.task_wav
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public byte[] getTaskWav() {
        return taskWav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_wav
     *
     * @param taskWav the value for task.task_wav
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setTaskWav(byte[] taskWav) {
        this.taskWav = taskWav;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_tag
     *
     * @return the value of task.task_tag
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public byte[] getTaskTag() {
        return taskTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_tag
     *
     * @param taskTag the value for task.task_tag
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setTaskTag(byte[] taskTag) {
        this.taskTag = taskTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task.task_textgrid
     *
     * @return the value of task.task_textgrid
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public byte[] getTaskTextgrid() {
        return taskTextgrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task.task_textgrid
     *
     * @param taskTextgrid the value for task.task_textgrid
     *
     * @mbggenerated Mon Aug 25 13:54:58 CST 2014
     */
    public void setTaskTextgrid(byte[] taskTextgrid) {
        this.taskTextgrid = taskTextgrid;
    }
}